### ISSUE TITLE
Remove hyperlink to doc.silverstripe.org

### ISSUE THREAD

**Issue by emteknetnz** [silverstripe/rhino#28]
When the repository is `doc.silverstripe.org` it's automatically hyperlinked when it shouldn't be

![image](https://github.com/silverstripe/rhino/assets/4809037/6931668e-1c39-4fdd-8ddb-09f2d3290d8f)

## PRs
- https://github.com/silverstripe/rhino/pull/29

**Comment by GuySartorelli** [comment]
PR merged, reassigned to Steve to deploy rhino

**Comment by emteknetnz** [comment]
Done
