### ISSUE TITLE
Use silverstripe/supported-modules

### ISSUE THREAD

**Issue by emteknetnz** [silverstripe/rhino#3]
Currently rhino runs off a hardcoded list for the modules it pulls information for

This isn't great because it includes some unsupported modules in the builds list and we waste time remedying them

It should instead use silverstripe/supported-modules

~~Note that `silverstripe/supported-modules` doesn't list some repositories we care about such as the gha* repositories. Either they should be added to the supported-modules JSON, or we need to keep them hardcoded here.~~ - That's no longer relevant as of https://github.com/silverstripe/rhino/issues/17

## Acceptance criteria
- Rhino is updated to fetch supported modules from `silverstripe/supported-modules` repo
- Rhino honours considers the difference in support levels between CMS 4 and CMS 5.
- [confluence docs about setting up new repos](https://silverstripe.atlassian.net/wiki/spaces/CMS/pages/3030679981/Setting+up+a+new+GitHub+repository) doesn't explicitly mention Rhino, since that's covered by supported-modules.
    - Note that the version of the supported modules repo we'll get will be locked into the composer.lock file... maybe update these docs to run `composer update silverstripe/supported-modules` in rhino and redeploy it.

## PRs
- https://github.com/silverstripe/rhino/pull/24
- https://github.com/silverstripe/supported-modules/pull/30
- https://github.com/silverstripe/rhino/pull/25
- https://github.com/silverstripe/supported-modules/pull/31
- https://github.com/silverstripe/rhino/pull/26

## Post merge supported-modules PR
- [x] Run composer update again and create a new rhino PR and deploy that

**Comment by GuySartorelli** [comment]
New PR merged. Reassigned to Steve for deployment.

**Comment by emteknetnz** [comment]
Have tested builds + merge-up jobs on UAT, all working. Have deployed to prod. Closing
